service: dog-ceo-api-node

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

#custom:
#  s3Bucket: dog-ceo-stanford-files # ${self:custom.s3Bucket}

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  listallbreeds:
    handler: images/listallbreeds.listallbreeds
    events:
      - http:
          path: breeds/list/all
          method: get
          cors: true