service: dog-ceo-api-node

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  listallbreeds:
    handler: images/listallbreeds.listallbreeds
    events:
      - http:
          path: breeds/list/all
          method: get
          cors: true