service: dog-ceo-api-node

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline
  - serverless-s3-sync

#custom:
#  s3Bucket: dog-ceo-stanford-files # ${self:custom.s3Bucket}

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

custom:
  s3Sync:
    - bucketName: dog-ceo-api-static-content
      localDir: static-content

resources:
  Resources:
    Json:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dog-ceo-api-static-content

functions:
  listAllBreeds:
    handler: images/listallbreeds.listallbreeds
    events:
      - http:
          path: breeds/list/all
          method: get
          cors: true
  listBreeds:
    handler: images/listbreeds.listbreeds
    events:
      - http:
          path: breeds/list
          method: get
          cors: true
  listSubBreeds:
    handler: images/listsubbreeds.listsubbreeds
    events:
      - http:
          path: breed/{breed}/list
          method: get
          cors: true
  randomImageAnyBreed:
    handler: images/randomimageanybreed.randomimageanybreed
    events:
      - http:
          path: breeds/image/random
          method: get
          cors: true
  allBreedImages:
    handler: images/allbreedimages.allbreedimages
    events:
      - http:
          path: breed/{breed}/images
          method: get
          cors: true
  allSubBreedImages:
    handler: images/allbreedimages.allbreedimages
    events:
      - http:
          path: breed/{breed}/{breed2}/images
          method: get
          cors: true
  randomImageFromBreed:
    handler: images/randomimagefrombreed.randomimagefrombreed
    events:
      - http:
          path: breed/{breed}/images/random
          method: get
          cors: true
  randomImageFromSubBreed:
    handler: images/randomimagefrombreed.randomimagefrombreed
    events:
      - http:
          path: breed/{breed}/{breed2}/images/random
          method: get
          cors: true